export const user = {
  name: "Nguyễn Trường Giang",
  username: "foggo",
  dob: "14-11-2005",
  job: "Sinh viên",
  company: "PTIT",
  profilepic: "https://avatars.githubusercontent.com/u/108665939?s=96&v=4",
  email: "GiangNT.B23CC055@stu.ptit.edu.vn",
  appointmentList: [
    {
      id: 1,
      department: "Phòng Tư vấn thiết kế",
      departmentCode: "PTVTK",
      datetime: "2024-10-28T08:00:00.000+07:00",
      staff: {
        id: 1,
        name: "Thái Minh Quân",
        position: "Phó trưởng phòng",
        email: "tmq@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      purpose: "Trao đổi công việc",
      note: "Gặp trực tiếp",
      status: "finished",
    },
    {
      id: 2,
      department: "Phòng Nghiên cứu phát triển công nghệ số",
      departmentCode: "PNCPTCNS",
      datetime: "2024-10-30T13:00:00.000+07:00",
      staff: {
        id: 1,
        name: "Đặng Anh Tuấn",
        position: "Phó trưởng phòng",
        email: "dat@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      purpose: "Trao đổi công việc",
      note: "",
      status: "pending",
    },
    {
      id: 3,
      department: "Phòng Tổng hợp",
      departmentCode: "PTH",
      datetime: "2024-11-01T09:00:00.000+07:00",
      staff: {
        id: 1,
        name: "Vũ Thị Lan Hương",
        position: "Trưởng phòng",
        email: "vtlh@example.com",
        phoneNumber: "0987654321",
        teleChatID: "abcdxyz123456",
      },
      purpose: "Trao đổi công việc",
      note: "",
      status: "pending",
    },
    {
      id: 4,
      department: "Phòng Tổng hợp",
      departmentCode: "PTH",
      datetime: "2024-11-01T10:00:00.000+07:00",
      staff: {
        id: 2,
        name: "Nguyễn Văn An",
        position: "Nhân viên",
        email: "nva@example.com",
        phoneNumber: "0987654322",
        teleChatID: "abcdxyz123457",
      },
      purpose: "Báo cáo tiến độ dự án",
      note: "Meeting online",
      status: "confirmed",
    },
    {
      id: 5,
      department: "Phòng Tư vấn thiết kế",
      departmentCode: "PTVTK",
      datetime: "2024-11-02T15:00:00.000+07:00",
      staff: {
        id: 3,
        name: "Trần Thị Bình",
        position: "Trưởng nhóm",
        email: "ttb@example.com",
        phoneNumber: "0987654323",
        teleChatID: "abcdxyz123458",
      },
      purpose: "Review thiết kế",
      note: "Mang theo tài liệu",
      status: "confirmed",
    },
  ],
};
